[package]
name = "eruption-gui"
version = "0.0.6"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A GUI for the Eruption Linux user-mode driver"
repository = "https://github.com/X3n0m0rph59/eruption-roccat-vulcan.git"
homepage = "https://github.com/X3n0m0rph59/eruption-roccat-vulcan"
license = "GPLv3+"
readme = "README.md"

[dependencies]
clap = "3.0.0-beta.2"
clap_derive = "3.0.0-beta.2"
colored = "2.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
libc = "0.2.86"
nix = "0.19.1"
rayon = "1.5.0"
walkdir = "2.3.1"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = { version = "1.0.62" }
tokio = { version = "1.2.0", features = ["full"] }
tracing = "0.1.23"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
toml = "0.5.8"
itertools = "0.10.0"
lazy_static = "1.4.0"
palette = "0.5.0"
thiserror = "1.0.23"
eyre = "0.6.5"
color-eyre = "0.5.10"
paste = "1.0"
dbus = "0.9.1"
dbus-tokio = "0.7.3"

[dependencies.gtk]
version = "0.9.2"
features = ["v3_22"]

[dependencies.sourceview]
version = "0.9.0"
features = ["v3_22"]

[dependencies.gdk]
version = "0.13.2"
features = ["v3_22"]

[dependencies.gdk-pixbuf]
version = "0.9.0"

[dependencies.glib]
version = "0.10.3"

[dependencies.pango]
version = "0.9.1"

[dependencies.pangocairo]
version = "0.10.0"

[dependencies.cairo-rs]
version = "0.9.1"

[dependencies.gio]
version = "0.9.1"
features = ["v2_44"]

[dev-dependencies]
tokio = { version = "1.2.0", features = ["test-util"] }
