[package]
name = "eruption-debug-tool"
version = "0.0.9"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "A CLI utility to debug USB HID devices"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://github.com/X3n0m0rph59/eruption"
license = "GPLv3+"
readme = "README.md"

[dependencies]
clap =  { version = "3.0.0-beta.2", features = ["derive"] }
clap_generate = "3.0.0-beta.2"
colored = "2.0.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
libc = "0.2.86"
nix = "0.20.0"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.63"
tokio = { version = "1.2.0", features = ["full"] }
tracing = "0.1.25"
tracing-futures = "0.2.5"
tracing-subscriber = "0.2.16"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
toml = "0.5.8"
thiserror = "1.0.24"
eyre = "0.6.5"
color-eyre = "0.5.10"
paste = "1.0.4"
hexdump = "0.1.0"
hidapi = { git = "https://github.com/ruabmbua/hidapi-rs.git", branch = "master" }
udev = "0.6.0"

[dev-dependencies]
tokio = { version = "1.2.0", features = ["test-util"] }
